### ISSUE TITLE
Disable the `Layout/RescueEnsureAlignment` Cop

### ISSUE THREAD

**Issue by makmic** [makandra/makandra-rubocop#16]
There are multiple scenarios where the `Layout/RescueEnsureAlignment` cop urges me to align my ensure block in an ugly way. I vote to disable the cop for our makandra fork.

### Examples

* For variable assignments, the cop tries to align the `ensure` block with the `do` keyword.
```
my_block = do
  # do stuff
ensure
  # other stuff
end
```
* For memoized method, the cop tries to align the `ensure` block with the `def` keyword.
```
memoized def foo
  # do stuff
ensure
  # other stuff
end
```

**Comment by denzelem** [comment]
So this is a bug in Rubocop (maybe related to https://github.com/rubocop-hq/rubocop/pull/7531 or https://github.com/rubocop-hq/rubocop/issues/7470) and we want to temporary disable it until it's fixed in the upstream?

**Comment by denzelem** [comment]
This was a regression of #7, we disabled the cop again until it is really fixed.
