### ISSUE TITLE
Disable Lint/EmptyWhen

### ISSUE THREAD

**Issue by denzelem** [makandra/makandra-rubocop#18]
I would suggest to disable the `Lint/EmptyWhen` (https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/EmptyWhen) to allow comments.

Example:

```
case response.code
when 200
  # nothing to do, everything is fine
when 403
  Rails.logger.info('Here was an 403 error')
else
  raise ArgumentError, "Unknown response code '#{response.code}'"
end
```

Wdyt?

**Comment by triskweline** [comment]
The empty `when` with a comment is such a thoughful thing to do.
