### ISSUE TITLE
Disable Naming/RescuedExceptionsVariableName, or change its default

### ISSUE THREAD

**Issue by foobear** [makandra/makandra-rubocop#19]
Rubocop changed the default setting for Naming/RescuedExceptionsVariableName in 0.67.1 to require captured exceptions to be called `e`.

There is [some kind of reasoning](https://github.com/rubocop-hq/rubocop/pull/6881) behind this, but I consider `e` a terrible variable name.
I believe we usually use `error`, so we could change the default to that. Or, since we probably don not want to prevent "proper" names like `parse_error`, we could just disable the cop.

:+1: Disable
:rocket: Change default to `error`
:-1: Keep as is

**Comment by triskweline** [comment]
Vote to disable the cop.

**Comment by jakobscholz** [comment]
:rocket: would not allow 

```
...
rescue ArgumentError > argument_error
...
rescue StandardError > error
...
end
