### ISSUE TITLE
Unused method argument in abstract method

### ISSUE THREAD

**Issue by dastra-mak** [makandra/makandra-rubocop#2]
I noticed that rubocop will try to prefix unused method arguments with underscores. In general I agree with this, but I found a case in which I don't want the prefix. This is with abstract methods which should just define the signature of a method.

```
-        def pick_value(record)
+        def pick_value(_record)
           raise NotImplementedError
         end
```

Should we just accept the fact that the arguments are prefixed in this situation or disable the cop?

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UnusedMethodArgument

**Comment by triskweline** [comment]
I think if we're going to prefix unused args, it's OK to also have them prefixed in this example. After all, they're unused in the interface definition.

BTW Rubocop's style guide is [against abstract methods](https://github.com/rubocop-hq/ruby-style-guide#duck-typing), but I think they are very valuable for communicating an intended interface.

**Comment by foobear** [comment]
Ruby will print warnings (when enabled) for unused local variables, unless they are prefixed with an underscore. I agree with @triskweline: if we want to prefix those, unused method arguments should also be prefixed for consistency (even though Ruby won't warn for them).

I don't consider difference in argument names an issue. When overwriting methods, method arguments to not need to have the same names.

Also agreed on the point of abstract methods and making an intended API clearly visible (though it's outside the scope here).

**Comment by judithroth** [comment]
We have not used the prefix with underscore for unused variables in our projects yet. For me it does not add value, because my editor highlighting shows unused variables very clearly.
So I vote for disabling the cop.

**Comment by kratob** [comment]
Vote for "keep enabled", especially since Ruby and some IDEs show unused variables, and I'd rather not see unwarranted warnings.
