### ISSUE TITLE
Maybe add a default config for rubocop-rspec 

### ISSUE THREAD

**Issue by denzelem** [makandra/makandra-rubocop#21]
It makes sense to evaluate the benefits of adding a makandra default config for `rubocop-rspec`. We did the same with `rubocop-rails` a few months ago.

@foobear Any veto for the evaluation?

**Comment by foobear** [comment]
Agreed, this makes sense. :+1:

**Comment by denzelem** [comment]
This is a summary from a middle sized project. I think some of the cops are useful, I will try to create a PR with the ones that we can use.

* 1666  [RSpec/MessageSpies](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/MessageSpies)
* 920   [RSpec/ContextWording](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ContextWording)
* 807   [RSpec/MultipleExpectations](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/MultipleExpectations)
* 704   [RSpec/NamedSubject](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/NamedSubject)
* 558   [RSpec/ExampleLength](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ExampleLength)
* 493   [RSpec/ExpectInHook](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ExpectInHook)
* 434   [RSpec/EmptyLineAfterFinalLet](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/EmptyLineAfterFinalLet)
* 428   [RSpec/InstanceVariable](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/InstanceVariable)
* 340   [RSpec/EmptyLineAfterSubject](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/EmptyLineAfterSubject)
* 280   [RSpec/VerifiedDoubles](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/VerifiedDoubles)
* 262   [RSpec/NestedGroups](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/NestedGroups)
* 243   [RSpec/EmptyLineAfterHook](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/EmptyLineAfterHook)
* 201   [RSpec/HookArgument](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/HookArgument)
* 187   [RSpec/DescribedClass](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/DescribedClass)
* 174   [RSpec/AnyInstance](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/AnyInstance)
* 162   [RSpec/SharedExamples](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/SharedExamples)
* 142   [RSpec/LeadingSubject](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/LeadingSubject)
* 130   [RSpec/SubjectStub](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/SubjectStub)
* 88    [RSpec/ImplicitExpect](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ImplicitExpect)
* 73    [RSpec/BeforeAfterAll](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/BeforeAfterAll)
* 52    [RSpec/ScatteredLet](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ScatteredLet)
* 42    [RSpec/MessageChain](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/MessageChain)
* 40    [RSpec/LetBeforeExamples](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/LetBeforeExamples)
* 34    [RSpec/ExampleWording](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ExampleWording)
* 33    [RSpec/ReturnFromStub](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ReturnFromStub)
* 23    [RSpec/FilePath](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/FilePath)
* 22    [RSpec/DescribeClass](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/DescribeClass)
* 17    [RSpec/ReceiveCounts](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ReceiveCounts)
* 13    [RSpec/RepeatedDescription](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/RepeatedDescription)
* 12    [RSpec/EmptyLineAfterExampleGroup](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/EmptyLineAfterExampleGroup)
* 12    [RSpec/HooksBeforeExamples](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/HooksBeforeExamples)
* 12    [RSpec/ImplicitSubject](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ImplicitSubject)
* 8     [RSpec/NotToNot](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/NotToNot)
* 8     [RSpec/RepeatedExample](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/RepeatedExample)
* 7     [RSpec/IteratedExpectation](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/IteratedExpectation)
* 7     [RSpec/MultipleDescribes](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/MultipleDescribes)
* 2     [RSpec/ExpectChange](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ExpectChange)
* 2     [RSpec/MissingExampleGroupArgument](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/MissingExampleGroupArgument)
* 2     [RSpec/OverwritingSetup](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/OverwritingSetup)
* 2     [RSpec/ScatteredSetup](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ScatteredSetup)
* 2     [RSpec/VoidExpect](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/VoidExpect)
* 1     [RSpec/BeEql](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/BeEql)
* 1     [RSpec/EmptyExampleGroup](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/EmptyExampleGroup)
* 1     [RSpec/ExpectActual](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ExpectActual)
* 1     [RSpec/ExpectOutput](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/ExpectOutput)
* 1     [RSpec/MultipleSubjects](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/MultipleSubjects)
