### ISSUE TITLE
Discussion: Rails/LinkToBlank

### ISSUE THREAD

**Issue by foobear** [makandra/makandra-rubocop#30]
Rubocop [expects](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/LinkToBlank) a `rel="noopener"` for links with `target="_blank"` because of legacy security reasons.

```
app/example.rb:12:34: C: [Correctable] Rails/LinkToBlank: Specify a :rel option containing noopener.
    link_to(text, url, target: '_blank')
                       ^^^^^^^^^^^^^^^^
```

This is only relevant for IE11, since the [HTML spec was changed](https://github.com/whatwg/html/issues/4078) and all modern browsers have adjusted.

I vote for disabling this cop in our default config, since we by default do not support IE11.

:+1: Disable cop
:-1: Keep cop enabled

**Comment by codener** [comment]
Released as 7.2.0.
