### ISSUE TITLE
Disable Naming/BlockForwarding

### ISSUE THREAD

**Issue by foobear** [makandra/makandra-rubocop#37]
Ruby 3.1 introduced support for anonymous blocks.
Rubocop by default enforces the anonymous style, if possible: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/BlockForwarding

IMO there are valid cases where we want to give meaningful names to block arguments.
I'm not against using anonymous blocks per se, so I suggest to disable that cop in our default config.

Vote:
:+1: Disable
:-1: Keep enabled
:confused: Keep enabled, but set `EnforcedStyle: explicit`

**Comment by brunosedler** [comment]
Disabled in https://github.com/makandra/makandra-rubocop/commit/1e4f0824607ebf7061fb5d48a5bc734ecc9da984 and released with Version 9.1.0
