### ISSUE TITLE
Style of raise

### ISSUE THREAD

**Issue by dastra-mak** [makandra/makandra-rubocop#4]
For me it was unexpected that Errors should not be instantiated with the message. In my opinion it's more common to raise with new.

```
-      raise WrongHeaderError.new(message)
+      raise WrongHeaderError, message
```
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RaiseArgs

Aspects to consider:
- raise with message as argument is canonical
- only canonical Errors can be raised this way
- new does not allow to provide a backtrace https://github.com/rubocop-hq/ruby-style-guide#exception-class-messages

Should we raise with instantiation or not?

**Comment by triskweline** [comment]
If I have an error class with a custom constructor, will makandra-rubocop allow the instantiation?

**Comment by dastra-mak** [comment]
No, it will complain about

```
raise CustomError.new('message')
```

but not about


```
raise CustomError.new('message', :other)
```

Probably that's good enough for us.

**Comment by foobear** [comment]
For all I know, `raise ErrorClass, error_message` is the preferred way across the community.

If you want to raise a custom error that accepts other arguments than the message, the constructor is possibly different (maybe message is not the 1st argument) and can not be supported by `raise`. There are valid cases for this and you'd then say something like

```ruby
raise IdentifierError.new('Record has different canonical identifier', identifier)
```

Rubocop will not complain about this, so I vote for keeping as is.

**Comment by triskweline** [comment]
Vote for keeping.

**Comment by dastra-mak** [comment]
I agree with keeping
