### ISSUE TITLE
Disable Capybara/ClickLinkOrButtonStyle

### ISSUE THREAD

**Issue by foobear** [makandra/makandra-rubocop#49]
This cop is configured as `pending`, but since we enable pending cops by default, it's enabled in our environments.

It will be [deprecated in rubocop-capybara 3.0 anyway](https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaraclicklinkorbuttonstyle) and I personally don't think it actually improves much.

Effectively, it currently adds noise which is irrelevant some time soon.
IMO we should just disable it.

**Comment by codener** [comment]
Agreed.

**Comment by codener** [comment]
test comment

**Comment by codener** [comment]
test comment
